-- ============================================================
-- INVENTORY — per-project live site stock. ADDITIVE: creates ONE new table,
-- touches nothing else. Fills from delivered POs; site engineers deduct usage;
-- low stock drives the AI Telegram alert. Safe to re-run.
-- ============================================================
drop table if exists inventory cascade;

create table inventory (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  material_id   bigint references materials(id) on delete set null,
  item_name     text not null,
  unit          text,
  quantity      numeric(14,2) not null default 0,
  reorder_level numeric(14,2) not null default 0,
  location      text default 'Site store',
  updated_at    timestamptz not null default now(),
  unique (project_id, item_name)
);
alter table inventory enable row level security;

-- Backfill from goods already received (delivered/invoiced/paid/partial POs).
insert into inventory (project_id, material_id, item_name, unit, quantity, reorder_level, location)
select po.project_id,
       max(poi.material_id)                       as material_id,
       coalesce(m.name, poi.description)          as item_name,
       coalesce(max(m.unit), max(poi.unit))       as unit,
       sum(poi.quantity)                          as quantity,
       greatest(ceil(sum(poi.quantity) * 0.3), 5) as reorder_level,
       'Site store'
from purchase_order_items poi
join purchase_orders po on po.id = poi.po_id
left join materials m on m.id = poi.material_id
where po.status in ('delivered', 'invoiced', 'paid', 'partially_delivered')
group by po.project_id, coalesce(m.name, poi.description)
on conflict (project_id, item_name) do update
  set quantity = excluded.quantity, reorder_level = excluded.reorder_level;

-- Simulate a little on-site usage so the tab + alert show OK / Low / Out states.
update inventory set quantity = 0             where item_name ilike 'uPVC Tee%';
update inventory set quantity = 3             where item_name ilike 'Wash Basin%';
update inventory set quantity = reorder_level where item_name ilike 'HDPE Pipe 63mm%';
